// <auto-generated />
using System;
using GestiónDeImagenIA_Back.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestiónDeImagenIA_Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730180218_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GestiónDeImagenIA_Back.Core.Entities.Cliente", b =>
                {
                    b.Property<int>("Id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre_cliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_comprobante")
                        .HasColumnType("int");

                    b.HasKey("Id_cliente");

                    b.HasIndex("id_comprobante");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("GestiónDeImagenIA_Back.Core.Entities.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BeneficiarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaTransferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("HoraTransferencia")
                        .HasColumnType("time(6)");

                    b.Property<string>("Moneda")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumeroOperacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Referencia")
                        .HasColumnType("longtext");

                    b.Property<int>("RemitenteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.HasIndex("RemitenteId");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("GestiónDeImagenIA_Back.Core.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CbuAlias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CuitDni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("GestiónDeImagenIA_Back.Core.Entities.Cliente", b =>
                {
                    b.HasOne("GestiónDeImagenIA_Back.Core.Entities.Comprobante", "comprobante")
                        .WithMany()
                        .HasForeignKey("id_comprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("comprobante");
                });

            modelBuilder.Entity("GestiónDeImagenIA_Back.Core.Entities.Comprobante", b =>
                {
                    b.HasOne("GestiónDeImagenIA_Back.Core.Entities.Persona", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestiónDeImagenIA_Back.Core.Entities.Persona", "Remitente")
                        .WithMany()
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiario");

                    b.Navigation("Remitente");
                });
#pragma warning restore 612, 618
        }
    }
}
